// <auto-generated>
//   tools/gen_formation_catalog.py wrote this from the modal geometry of the real
//   eFootball team formations in build/master.db. Do not hand-edit: re-run the tool.
// </auto-generated>
using System.Collections.Generic;

namespace ML.App;

/// <summary>
/// The formations the Tactics screen offers, independent of what this world's
/// formation_slots happens to hold — and the name for each shape the geometry reads as.
///
/// A world built from the player's own install used to carry no formation geometry at all:
/// dt200 has it, game_world.py just never read it, so the Set Formation list was whatever
/// four shapes career_seed rotated through. game_world.py reads the real tables now; this
/// catalogue still names them, and still fills the list in a world built before that fix.
/// </summary>
public static class FormationCatalog
{
    /// <summary>One slot of a template: the game's role code, and its place on the pitch
    /// in formation_slots coordinates (x 12-92 across, y 3-43 up).</summary>
    public readonly record struct Slot(int Role, int X, int Y);

    /// <summary>A named shape and its eleven slots, in slot_index order (0 is the GK).</summary>
    public sealed record Template(string Name, IReadOnlyList<Slot> Slots);

    /// <summary>Every template, back three first, then four, then five.</summary>
    public static IReadOnlyList<Template> All { get; } = new Template[]
    {
        // 3-4-3: CB CB CB DMF CMF CMF AMF RWF LWF CF   (2 real clubs)
        new("3-4-3", new Slot[]
        {
            new(0, 52, 3),   // GK
            new(1, 52, 11),   // CB
            new(1, 76, 11),   // CB
            new(1, 28, 11),   // CB
            new(4, 52, 19),   // DMF
            new(5, 72, 25),   // CMF
            new(5, 32, 25),   // CMF
            new(8, 52, 31),   // AMF
            new(10, 84, 39),   // RWF
            new(9, 20, 39),   // LWF
            new(12, 52, 43),   // CF
        }),
        // 3-5-2: CB CB CB DMF CMF CMF RMF LMF CF CF   (22 real clubs)
        new("3-5-2", new Slot[]
        {
            new(0, 52, 3),   // GK
            new(1, 52, 11),   // CB
            new(1, 72, 11),   // CB
            new(1, 32, 11),   // CB
            new(4, 52, 21),   // DMF
            new(5, 68, 23),   // CMF
            new(5, 36, 23),   // CMF
            new(7, 88, 27),   // RMF
            new(6, 16, 27),   // LMF
            new(12, 64, 43),   // CF
            new(12, 40, 43),   // CF
        }),
        // 3-1-4-2: CB CB CB CMF CMF CMF RMF LMF CF CF   (16 real clubs)
        new("3-1-4-2", new Slot[]
        {
            new(0, 52, 3),   // GK
            new(1, 52, 11),   // CB
            new(1, 72, 11),   // CB
            new(1, 32, 11),   // CB
            new(5, 52, 21),   // CMF
            new(5, 68, 27),   // CMF
            new(5, 36, 27),   // CMF
            new(7, 88, 27),   // RMF
            new(6, 16, 27),   // LMF
            new(12, 64, 43),   // CF
            new(12, 40, 43),   // CF
        }),
        // 3-4-1-2: CB CB CB CMF CMF RMF LMF AMF CF CF   (42 real clubs)
        new("3-4-1-2", new Slot[]
        {
            new(0, 52, 3),   // GK
            new(1, 52, 11),   // CB
            new(1, 72, 11),   // CB
            new(1, 32, 11),   // CB
            new(5, 64, 21),   // CMF
            new(5, 40, 21),   // CMF
            new(7, 88, 25),   // RMF
            new(6, 16, 25),   // LMF
            new(8, 52, 33),   // AMF
            new(12, 64, 43),   // CF
            new(12, 40, 43),   // CF
        }),
        // 3-4-2-1: CB CB CB CMF CMF RMF LMF SS SS CF   (220 real clubs)
        new("3-4-2-1", new Slot[]
        {
            new(0, 52, 3),   // GK
            new(1, 52, 11),   // CB
            new(1, 72, 11),   // CB
            new(1, 32, 11),   // CB
            new(5, 64, 21),   // CMF
            new(5, 40, 21),   // CMF
            new(7, 88, 25),   // RMF
            new(6, 16, 25),   // LMF
            new(11, 68, 35),   // SS
            new(11, 36, 35),   // SS
            new(12, 52, 43),   // CF
        }),
        // 3-5-1-1: CB CB CB DMF CMF CMF RMF LMF AMF CF   (2 real clubs)
        new("3-5-1-1", new Slot[]
        {
            new(0, 52, 3),   // GK
            new(1, 52, 11),   // CB
            new(1, 72, 11),   // CB
            new(1, 32, 11),   // CB
            new(4, 52, 21),   // DMF
            new(5, 68, 23),   // CMF
            new(5, 36, 23),   // CMF
            new(7, 88, 27),   // RMF
            new(6, 16, 27),   // LMF
            new(8, 52, 33),   // AMF
            new(12, 52, 43),   // CF
        }),
        // 4-3-3: CB CB RB LB DMF CMF CMF RWF LWF CF   (115 real clubs)
        new("4-3-3", new Slot[]
        {
            new(0, 52, 3),   // GK
            new(1, 64, 11),   // CB
            new(1, 40, 11),   // CB
            new(3, 88, 13),   // RB
            new(2, 16, 13),   // LB
            new(4, 52, 19),   // DMF
            new(5, 68, 25),   // CMF
            new(5, 36, 25),   // CMF
            new(10, 84, 39),   // RWF
            new(9, 20, 39),   // LWF
            new(12, 52, 43),   // CF
        }),
        // 4-4-2: CB CB RB LB CMF CMF RMF LMF CF CF   (160 real clubs)
        new("4-4-2", new Slot[]
        {
            new(0, 52, 3),   // GK
            new(1, 64, 11),   // CB
            new(1, 40, 11),   // CB
            new(3, 88, 13),   // RB
            new(2, 16, 13),   // LB
            new(5, 64, 25),   // CMF
            new(5, 40, 25),   // CMF
            new(7, 88, 27),   // RMF
            new(6, 16, 27),   // LMF
            new(12, 64, 43),   // CF
            new(12, 40, 43),   // CF
        }),
        // 4-1-4-1: CB CB RB LB DMF CMF CMF RMF LMF CF   (34 real clubs)
        new("4-1-4-1", new Slot[]
        {
            new(0, 52, 3),   // GK
            new(1, 64, 11),   // CB
            new(1, 40, 11),   // CB
            new(3, 88, 13),   // RB
            new(2, 16, 13),   // LB
            new(4, 52, 19),   // DMF
            new(5, 64, 27),   // CMF
            new(5, 40, 27),   // CMF
            new(7, 88, 29),   // RMF
            new(6, 16, 29),   // LMF
            new(12, 52, 43),   // CF
        }),
        // 4-2-1-3: CB CB RB LB DMF DMF AMF RWF LWF CF   (156 real clubs)
        new("4-2-1-3", new Slot[]
        {
            new(0, 52, 3),   // GK
            new(1, 64, 11),   // CB
            new(1, 40, 11),   // CB
            new(3, 88, 13),   // RB
            new(2, 16, 13),   // LB
            new(4, 68, 21),   // DMF
            new(4, 36, 21),   // DMF
            new(8, 52, 31),   // AMF
            new(10, 88, 35),   // RWF
            new(9, 16, 35),   // LWF
            new(12, 52, 43),   // CF
        }),
        // 4-2-2-2: CB CB RB LB CMF CMF RMF LMF CF CF   (16 real clubs)
        new("4-2-2-2", new Slot[]
        {
            new(0, 52, 3),   // GK
            new(1, 64, 11),   // CB
            new(1, 40, 11),   // CB
            new(3, 88, 13),   // RB
            new(2, 16, 13),   // LB
            new(5, 64, 21),   // CMF
            new(5, 40, 21),   // CMF
            new(7, 84, 31),   // RMF
            new(6, 20, 31),   // LMF
            new(12, 64, 43),   // CF
            new(12, 40, 43),   // CF
        }),
        // 4-2-3-1: CB CB RB LB DMF DMF RMF LMF AMF CF   (615 real clubs)
        new("4-2-3-1", new Slot[]
        {
            new(0, 52, 3),   // GK
            new(1, 64, 11),   // CB
            new(1, 40, 11),   // CB
            new(3, 88, 13),   // RB
            new(2, 16, 13),   // LB
            new(4, 64, 19),   // DMF
            new(4, 40, 19),   // DMF
            new(7, 84, 31),   // RMF
            new(6, 20, 31),   // LMF
            new(8, 52, 31),   // AMF
            new(12, 52, 43),   // CF
        }),
        // 4-3-1-2: CB CB RB LB CMF CMF CMF AMF CF CF   (10 real clubs)
        new("4-3-1-2", new Slot[]
        {
            new(0, 52, 3),   // GK
            new(1, 64, 11),   // CB
            new(1, 40, 11),   // CB
            new(3, 88, 13),   // RB
            new(2, 16, 13),   // LB
            new(5, 52, 23),   // CMF
            new(5, 72, 23),   // CMF
            new(5, 32, 23),   // CMF
            new(8, 52, 33),   // AMF
            new(12, 64, 43),   // CF
            new(12, 40, 43),   // CF
        }),
        // 4-3-2-1: CB CB RB LB CMF CMF CMF RWF LWF CF   (38 real clubs)
        new("4-3-2-1", new Slot[]
        {
            new(0, 52, 3),   // GK
            new(1, 64, 11),   // CB
            new(1, 40, 11),   // CB
            new(3, 88, 13),   // RB
            new(2, 16, 13),   // LB
            new(5, 52, 25),   // CMF
            new(5, 72, 25),   // CMF
            new(5, 32, 25),   // CMF
            new(10, 84, 39),   // RWF
            new(9, 20, 39),   // LWF
            new(12, 52, 43),   // CF
        }),
        // 4-4-1-1: CB CB RB LB CMF CMF RMF LMF AMF CF   (10 real clubs)
        new("4-4-1-1", new Slot[]
        {
            new(0, 52, 3),   // GK
            new(1, 64, 11),   // CB
            new(1, 40, 11),   // CB
            new(3, 88, 13),   // RB
            new(2, 16, 13),   // LB
            new(5, 64, 23),   // CMF
            new(5, 40, 23),   // CMF
            new(7, 88, 25),   // RMF
            new(6, 16, 25),   // LMF
            new(8, 52, 33),   // AMF
            new(12, 52, 43),   // CF
        }),
        // 4-1-2-1-2: CB CB RB LB CMF CMF CMF AMF CF CF   (16 real clubs)
        new("4-1-2-1-2", new Slot[]
        {
            new(0, 52, 3),   // GK
            new(1, 64, 11),   // CB
            new(1, 40, 11),   // CB
            new(3, 88, 13),   // RB
            new(2, 16, 13),   // LB
            new(5, 52, 19),   // CMF
            new(5, 68, 25),   // CMF
            new(5, 36, 25),   // CMF
            new(8, 52, 33),   // AMF
            new(12, 64, 43),   // CF
            new(12, 40, 43),   // CF
        }),
        // 4-2-2-1-1: CB CB RB LB DMF DMF RMF LMF AMF CF   (2 real clubs)
        new("4-2-2-1-1", new Slot[]
        {
            new(0, 52, 3),   // GK
            new(1, 64, 11),   // CB
            new(1, 40, 11),   // CB
            new(3, 88, 13),   // RB
            new(2, 16, 13),   // LB
            new(4, 64, 19),   // DMF
            new(4, 40, 19),   // DMF
            new(7, 84, 25),   // RMF
            new(6, 20, 25),   // LMF
            new(8, 52, 33),   // AMF
            new(12, 52, 43),   // CF
        }),
        // 5-3-2: CB CB CB RB LB DMF CMF CMF CF CF   (78 real clubs)
        new("5-3-2", new Slot[]
        {
            new(0, 52, 3),   // GK
            new(1, 52, 11),   // CB
            new(1, 72, 11),   // CB
            new(1, 32, 11),   // CB
            new(3, 88, 15),   // RB
            new(2, 16, 15),   // LB
            new(4, 52, 21),   // DMF
            new(5, 68, 27),   // CMF
            new(5, 36, 27),   // CMF
            new(12, 64, 43),   // CF
            new(12, 40, 43),   // CF
        }),
        // 5-4-1: CB CB CB RB LB CMF CMF RMF LMF CF   (3 real clubs)
        new("5-4-1", new Slot[]
        {
            new(0, 52, 3),   // GK
            new(1, 52, 11),   // CB
            new(1, 72, 11),   // CB
            new(1, 32, 11),   // CB
            new(3, 88, 15),   // RB
            new(2, 16, 15),   // LB
            new(5, 64, 25),   // CMF
            new(5, 40, 25),   // CMF
            new(7, 84, 25),   // RMF
            new(6, 20, 25),   // LMF
            new(12, 52, 41),   // CF
        }),
        // 5-3-1-1: CB CB CB RB LB DMF CMF CMF AMF CF   (10 real clubs)
        new("5-3-1-1", new Slot[]
        {
            new(0, 52, 3),   // GK
            new(1, 52, 11),   // CB
            new(1, 72, 11),   // CB
            new(1, 32, 11),   // CB
            new(3, 88, 15),   // RB
            new(2, 16, 15),   // LB
            new(4, 52, 21),   // DMF
            new(5, 68, 23),   // CMF
            new(5, 36, 23),   // CMF
            new(8, 52, 33),   // AMF
            new(12, 52, 43),   // CF
        }),
    };

    // Formations.ShapeOf clusters slots by depth, which over-splits a staggered line: a
    // 3-4-2-1 whose wide midfielders sit four units behind the central pair reads as
    // "3-2-2-2-1". This is the name each of those readings belongs to, so the shape the
    // screen prints matches the template the list offered.
    private static readonly Dictionary<string, string> Names = new()
    {
        ["3-1-2-1-2-1"] = "3-4-3",
        ["3-3-2-2"] = "3-5-2",
        ["3-1-4-2"] = "3-1-4-2",
        ["3-2-2-1-2"] = "3-4-1-2",
        ["3-2-2-2-1"] = "3-4-2-1",
        ["3-3-2-1-1"] = "3-5-1-1",
        ["4-1-2-2-1"] = "4-3-3",
        ["4-4-2"] = "4-4-2",
        ["4-1-4-1"] = "4-1-4-1",
        ["4-2-1-2-1"] = "4-2-1-3",
        ["4-2-2-2"] = "4-2-2-2",
        ["4-2-3-1"] = "4-2-3-1",
        ["4-3-1-2"] = "4-3-1-2",
        ["4-3-2-1"] = "4-3-2-1",
        ["4-4-1-1"] = "4-4-1-1",
        ["4-1-2-1-2"] = "4-1-2-1-2",
        ["4-2-2-1-1"] = "4-2-2-1-1",
        ["3-2-1-2-2"] = "5-3-2",
        ["3-2-4-1"] = "5-4-1",
        ["3-2-3-1-1"] = "5-3-1-1",
    };

    /// <summary>The formation name for a derived line reading, or null if nothing names it.</summary>
    public static string? NameFor(string derived) =>
        Names.TryGetValue(derived, out var name) ? name : null;

    /// <summary>True when this is one of the catalogue's own formation names.</summary>
    public static bool IsNamed(string name) => Names.ContainsValue(name);
}
