using System.Collections.ObjectModel;
using System.Globalization;
using System.Text;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Media;
using Avalonia.Media.Imaging;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Dapper;

namespace ML.App.ViewModels;

/// <summary>
/// Nationality -> flag bitmap, from assets/flag_map.json (generated by tools/build_flag_map.py,
/// which keeps tools/assign_uran_faces.py's NAT2CODE as the single source of the name->trigram
/// mapping). Loaded once, lazily; the json stores repo-relative paths which Visuals.LoadBitmap
/// resolves and caches. The repo root comes from the public MatchLauncher.FindRepoRoot walk —
/// the same walk-up-from-the-binary strategy Visuals uses privately. Anything missing (map file,
/// nationality, flag) degrades to null: no flag shown, never an error.
/// </summary>
internal static class NationFlags
{
    private static readonly Lazy<IReadOnlyDictionary<string, string>> Map = new(() =>
    {
        try
        {
            var root = MatchLauncher.FindRepoRoot();
            var path = root is null ? null : Path.Combine(root, "assets", "flag_map.json");
            if (path is null || !File.Exists(path)) return new Dictionary<string, string>();
            return System.Text.Json.JsonSerializer
                       .Deserialize<Dictionary<string, string>>(File.ReadAllText(path))
                   ?? new Dictionary<string, string>();
        }
        catch { return new Dictionary<string, string>(); }
    });

    /// <summary>Flag for a players.nationality value; null when unknown (the UI hides it).</summary>
    public static Bitmap? For(string? nationality)
    {
        if (string.IsNullOrWhiteSpace(nationality)) return null;
        // Key normalisation mirrors tools/assign_uran_faces.py: first '/' segment, lowercased,
        // then progressively accent-folded ("Türkiye" -> "turkiye", "Côte d'Ivoire" -> "cote divoire").
        var key = nationality.Split('/')[0].Trim().ToLowerInvariant();
        return Lookup(key) ?? Lookup(Fold(key)) ?? Lookup(Fold(key).Replace("'", ""));
    }

    private static Bitmap? Lookup(string key) =>
        Map.Value.TryGetValue(key, out var path) ? Visuals.LoadBitmap(path) : null;

    /// <summary>Strip accents and non-ASCII: "Türkiye" -> "turkiye".</summary>
    private static string Fold(string s)
    {
        var formD = s.Normalize(NormalizationForm.FormD);
        var sb = new StringBuilder(formD.Length);
        foreach (var ch in formD)
        {
            if (CharUnicodeInfo.GetUnicodeCategory(ch) != UnicodeCategory.NonSpacingMark && ch < 128)
                sb.Append(ch);
        }
        return sb.ToString();
    }
}

/// <summary>A club option in the Squad screen's browse-any-club picker.</summary>
public sealed record SquadClubOption(int TeamId, string Name);

// --- Squad (master-detail: roster grid + eFootball-style player card) -------------

/// <summary>
/// One roster row. Carries everything the card header needs so selecting a player only fetches
/// abilities. Condition defaults (fatigue 0, no injury) cover squads with no player_condition
/// rows yet — a fresh career reads as fully fit.
/// </summary>
public sealed record SquadEntry
{
    public long PlayerId { get; init; }
    public int Number { get; init; }
    public string Name { get; init; } = "";
    public string Position { get; init; } = "";
    public int Age { get; init; }
    public int Rating { get; init; }
    public string? Nationality { get; init; }
    /// <summary>Nationality flag (assets/dvx_flags via flag_map.json); null hides the Image.</summary>
    public Bitmap? Flag { get; init; }
    public bool HasFlag => Flag is not null;
    public string Playstyle { get; init; } = "Basic";
    public int Fatigue { get; init; }
    public int? InjuredUntil { get; init; }
    /// <summary>
    /// The matchday every availability question about this row is asked "as of" — the fixture the
    /// squad is being picked for. Stamped by LoadRoster so the row carries its own answer; 0 only
    /// before a ball has been kicked, when no injury can exist yet either.
    /// </summary>
    public int AsOfMatchday { get; init; }
    public int Morale { get; init; } = 50;

    public string MoraleFace => Morale >= 75 ? "😀" : Morale >= 60 ? "🙂" : Morale >= 40 ? "😐"
        : Morale >= 25 ? "🙁" : "😡";
    public string MoraleLabel => ML.Core.Selection.MoraleModel.Label(Morale);
    public int? HeightCm { get; init; }
    public int? WeightKg { get; init; }
    public Bitmap? Portrait { get; init; }
    public int? SkinTone { get; init; }
    public int? HairColor { get; init; }
    public IBrush SkinBrush => Visuals.SkinBrush(SkinTone);
    public IBrush HairBrush => Visuals.HairBrush(HairColor);
    public string Mark { get; init; } = "";
    public IBrush MarkBrush { get; init; } = CondGreen;

    /// <summary>0-100 dossier level; 100 for your own club. Gates the letter grade.</summary>
    public int Knowledge { get; init; } = 100;
    public string Grade => ML.Core.Development.AttributeKnowledge.GradeMasked(Rating, Knowledge);
    public IBrush RatingBrush => Knowledge >= 75 ? Visuals.RatingBrush(Rating) : Visuals.Brush("#8A93A2");
    public IBrush ConditionBrush => Fatigue < 20 ? CondGreen : Fatigue < 40 ? CondAmber : CondRed;

    /// <summary>What the fitness dot means, in words. A coloured circle with no reading is a
    /// puzzle: green/amber/red could be form, morale, contract or match sharpness.</summary>
    public string ConditionLabel => Fatigue < 20 ? "Fresh"
        : Fatigue < 40 ? "Carrying a few miles" : "Needs a rest";

    /// <summary>
    /// Still injured FOR THE MATCH IN QUESTION — the single truth behind the red badge, the
    /// Injured chip and the Absence line.
    /// THE BUG this shape exists to prevent: it used to read `InjuredUntil is not null`, and
    /// player_condition.injured_until_md is only ever cleared at season rollover. So an August
    /// hamstring that healed by September kept the cross lit, kept him on the Injured chip and
    /// kept the card saying "unavailable" all the way to April — the one question a roster
    /// exists to answer, wrong for most of the season. Availability is a COMPARISON against the
    /// matchday, exactly as PrepareMatchday, SuggestXi and the Tactics grid all do it
    /// (`InjuredUntilMd is int u &amp;&amp; u >= md`). Never reintroduce a null test here.
    /// </summary>
    public bool IsInjured => InjuredUntil is int u && u >= AsOfMatchday;

    /// <summary>Club fixtures he still has to sit out (0 = no ban) and what earned it.</summary>
    public int SuspendedMatches { get; init; }
    public string SuspendedReason { get; init; } = "";
    public bool IsSuspended => SuspendedMatches > 0;

    /// <summary>Cannot be picked for the match in question, for either reason — what the red
    /// badge in the grid lights for.</summary>
    public bool IsUnavailable => IsInjured || IsSuspended;

    /// <summary>Why the badge is lit: the ban, or the matchday he is due back for.</summary>
    public string InjuryTip => IsSuspended
        ? $"Suspended — {Session.SuspensionSpan(SuspendedMatches)} ({SuspendedReason})"
        : InjuredUntil is int u ? $"Out injured until matchday {u}" : "";

    /// <summary>The badge's glyph: a cross for the treatment room, a card for a ban.</summary>
    public string UnavailableGlyph => IsSuspended ? "▮" : "+";
    public string HeightDisplay => HeightCm is > 0 ? $"{HeightCm} cm" : "—";
    public string WeightDisplay => WeightKg is > 0 ? $"{WeightKg} kg" : "—";
    public string AgeDisplay => Age > 0 ? Age.ToString() : "—";

    private static readonly IBrush CondGreen = new SolidColorBrush(Color.Parse("#1F9D4D"));
    private static readonly IBrush CondAmber = new SolidColorBrush(Color.Parse("#E0A526"));
    private static readonly IBrush CondRed = new SolidColorBrush(Color.Parse("#D64545"));
}

/// <summary>One line of the card's Ability list, value coloured like an in-game rating.</summary>
public sealed record AbilityEntry(
    string Name, string Display, IBrush ValueBrush, IBrush BandBrush, bool ShowBand);

/// <summary>The player-card visual maths, shared by the Squad card and the Market profile.</summary>
public static class PlayerCard
{
    /// <summary>
    /// Hexagon radar vertices on the 200x200 card canvas: centre (100,100), axis k at angle
    /// k*60-90 deg, radius 78 spanning ability 40 (centre) to 99 (outer gridline).
    /// </summary>
    public static Points BuildRadarPoints((string Label, double Value)[] axes)
    {
        var pts = new Points();
        for (var k = 0; k < axes.Length; k++)
        {
            var radius = 78.0 * (Math.Clamp(axes[k].Value, 40.0, 99.0) - 40.0) / 59.0;
            var angle = (k * 60 - 90) * Math.PI / 180.0;
            pts.Add(new Point(100 + radius * Math.Cos(angle), 100 + radius * Math.Sin(angle)));
        }
        return pts;
    }

    // Rows a pure outfielder never uses; hidden from a GK's list alongside their gk_* priority.
    private static readonly string[] PureAttack = { "finishing", "offensive_awareness" };

    // The FM colour bands: poor / average / good / elite.
    private static readonly IBrush[] BandBrushes =
    {
        Visuals.Brush("#E05545"), Visuals.Brush("#E0A526"),
        Visuals.Brush("#8BE04A"), Visuals.Brush("#38B6FF"),
    };
    private static readonly IBrush MaskedBrush = Visuals.Brush("#3A4453");

    /// <summary>
    /// Ability rows for the card. Numbers mode shows the raw value; FM mode (P5) shows a
    /// colour band instead — and only for attributes your knowledge of the player has
    /// revealed. Unrevealed attributes show a dash in BOTH modes' FM variant.
    /// </summary>
    /// <summary>
    /// The ability list, knowledge-masked. Pass <paramref name="order"/> — the player's world
    /// reputation reveal order — and a famous man's headline abilities come first, so the pace
    /// and the finishing everyone already knows about are not hidden behind a dice roll.
    /// </summary>
    public static IReadOnlyList<AbilityEntry> BuildAbilityList(
        IReadOnlyDictionary<string, int> abilities, bool isGk,
        bool fmMode = false, int knowledge = 100, long playerId = 0,
        ML.Core.Development.RevealOrder? order = null)
    {
        var rows = isGk
            ? abilities.Where(a => a.Key.StartsWith("gk_")).OrderBy(a => a.Key)
                .Concat(abilities
                    .Where(a => !a.Key.StartsWith("gk_") && !PureAttack.Contains(a.Key))
                    .OrderBy(a => a.Key))
            : abilities.Where(a => !a.Key.StartsWith("gk_")).OrderBy(a => a.Key);
        return rows.Select(a =>
        {
            if (!fmMode)
            {
                return new AbilityEntry(TitleCase(a.Key), a.Value.ToString(),
                    Visuals.RatingBrush(a.Value), MaskedBrush, false);
            }
            var revealed = ML.Core.Development.AttributeKnowledge
                .IsRevealed(playerId, a.Key, knowledge, order);
            return revealed
                ? new AbilityEntry(TitleCase(a.Key), "", MaskedBrush,
                    BandBrushes[ML.Core.Development.AttributeKnowledge.Band(a.Value)], true)
                : new AbilityEntry(TitleCase(a.Key), "—", MaskedBrush, MaskedBrush, false);
        }).ToList();
    }

    /// <summary>snake_case attribute key → display name: "offensive_awareness" → "Offensive Awareness".</summary>
    public static string TitleCase(string snake) =>
        string.Join(' ', snake.Split('_', StringSplitOptions.RemoveEmptyEntries)
            .Select(w => w == "gk" ? "GK" : char.ToUpperInvariant(w[0]) + w[1..]));
}

/// <summary>
/// One line of the loans strip. PlayerId and Direction stay as fields (not baked into the
/// prose) so the row is still an entity: right-clicking it opens the same player menu the
/// roster grid uses, and Recall keys off Direction rather than a parsed string.
/// </summary>
public sealed record LoanRowVm(long PlayerId, string Name, string Direction, string Line)
{
    public bool IsOut => Direction == "out";
}

/// <summary>
/// A roster filter chip. IsActive drives the pressed look (Classes.active in the view) so the
/// selected filter is visible on the chip itself.
/// </summary>
public sealed partial class FilterChipVm : ObservableObject
{
    public FilterChipVm(string name) => Name = name;
    public string Name { get; }
    [ObservableProperty] private bool _isActive;
}

public sealed partial class SquadViewModel : PageViewModel, IFocusTarget
{
    private readonly Session _s;

    /// <summary>Re-resolve the selected player's portrait (after "Set photo…") — tier 0
    /// custom faces bypass every cache, so this shows the new image immediately.</summary>
    public void RefreshSelectedPortrait()
    {
        if (Selected is null) return;
        try
        {
            var por = _s.PortraitFor(Selected.PlayerId);
            var updated = Selected with { Portrait = por.Image };
            var ix = Rows.IndexOf(Selected);
            if (ix >= 0) Rows[ix] = updated;
            Selected = updated;
        }
        catch { /* cosmetic refresh must never throw */ }
    }

    public SquadViewModel(Session s)
    {
        _s = s;
        _fmMode = s.FmAttributeMode;   // backing field: no rebuild side-effect during ctor
        _viewTeamId = s.CurrentTeamId;

        BuildClubList();
        LoadRoster(_viewTeamId);   // stamps _asOfMd, which ApplyFilter's Injured chip reads
        ApplyFilter();
        Selected = Rows.FirstOrDefault();
        // an empty roster never fires OnSelectedChanged
        RefreshScoutButton();
        RefreshRenewButton(Selected);
        ReloadLoans();
    }

    /// <summary>
    /// The matchday this screen judges availability against: the next fixture is the Saturday the
    /// squad is being picked for. Recomputed inside LoadRoster rather than captured once in the
    /// ctor, so a matchday simmed elsewhere can never leave the injury badges reading last week.
    /// </summary>
    private void RefreshAsOfMatchday()
    {
        try
        {
            // Season complete (no fixture left): the honest reading is the matchday after the last
            // one played — the same question, one week on. 0 only when nothing has ever been
            // played, where there is no injury to judge anyway.
            _asOfMd = _s.NextFixture()?.Matchday
                      ?? _s.RecentResults(1).FirstOrDefault()?.Matchday + 1
                      ?? 0;
        }
        catch { _asOfMd = 0; }
    }

    /// <summary>Load a team's roster into <see cref="_all"/>. Own club or any browsed club.</summary>
    private void LoadRoster(int teamId)
    {
        _all.Clear();
        RefreshAsOfMatchday();   // every row is stamped with it, so availability is never stale
        // One query for the whole roster: playstyle + condition joined in. player_condition may
        // hold no rows yet (COALESCE covers it); the primary playstyle via subquery (kind-filtered
        // so the out-of-possession row never leaks in) so a player can't duplicate a roster row.
        var rows = _s.Db.Connection.Query<SquadRowDto>(
            """
            SELECT s.player_id PlayerId, s.squad_number Number, p.name Name, p.position Position,
                   COALESCE(p.age,0) Age, COALESCE(p.overall_rating,0) Rating,
                   p.nationality Nationality,
                   p.height_cm HeightCm, p.weight_kg WeightKg, COALESCE(p.game_face_path, p.real_face_path, p.portrait_path) PortraitPath,
                   (SELECT playstyle FROM player_playstyles WHERE player_id=s.player_id
                        AND kind='primary' LIMIT 1) Playstyle,
                   COALESCE(c.fatigue,0) Fatigue, c.injured_until_md InjuredUntil,
                   COALESCE(m.value,50) Morale,
                   COALESCE(b.matches,0) SuspendedMatches, COALESCE(b.reason,'') SuspendedReason
            FROM squad_members s
            JOIN players p ON p.id=s.player_id
            LEFT JOIN player_condition c ON c.player_id=s.player_id
            LEFT JOIN morale m ON m.player_id=s.player_id
            LEFT JOIN suspensions b ON b.player_id=s.player_id AND b.matches > 0
            WHERE s.team_id=@teamId
            ORDER BY s.slot
            """, new { teamId });

        var ownClub = teamId == _s.CurrentTeamId;
        foreach (var r in rows)
        {
            var por = _s.PortraitFor(r.PlayerId);
            int knowledge;
            if (ownClub) { knowledge = 100; }
            else
            {
                try { knowledge = _s.FmAttributeMode ? _s.KnowledgeOf(r.PlayerId) : 100; }
                catch { knowledge = 100; }
            }
            _all.Add(new SquadEntry
            {
                PlayerId = r.PlayerId,
                Number = r.Number,
                Name = r.Name,
                Position = r.Position,
                Age = r.Age,
                Rating = r.Rating,
                Nationality = r.Nationality,
                Flag = NationFlags.For(r.Nationality),
                Knowledge = knowledge,
                Playstyle = string.IsNullOrWhiteSpace(r.Playstyle) ? "Basic" : r.Playstyle,
                Fatigue = r.Fatigue,
                InjuredUntil = r.InjuredUntil,
                AsOfMatchday = _asOfMd,
                SuspendedMatches = r.SuspendedMatches,
                SuspendedReason = r.SuspendedReason,
                Morale = r.Morale,
                HeightCm = r.HeightCm,
                WeightKg = r.WeightKg,
                Portrait = por.Image,
                SkinTone = por.SkinTone,
                HairColor = por.HairColor,
                Mark = Visuals.PlayerMark(r.Name),
                // real skin tone behind the initials when there's no photo (the generic-face tier)
                MarkBrush = por.Image is null ? Visuals.SkinBrush(por.SkinTone) : Visuals.PositionBrush(r.Position),
            });
        }
    }

    // --- club browser (parity with ML.Web Squad): inspect any club's full roster -------
    public ObservableCollection<SquadClubOption> Clubs { get; } = new();
    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(IsOwnClub))]
    [NotifyPropertyChangedFor(nameof(ViewingOtherClub))]
    private SquadClubOption? _selectedClub;
    private int _viewTeamId;

    /// <summary>True when the shown roster is your own club — management commands only work then.</summary>
    public bool IsOwnClub => _viewTeamId == _s.CurrentTeamId;
    public bool ViewingOtherClub => !IsOwnClub;

    private void BuildClubList()
    {
        try
        {
            Clubs.Add(new SquadClubOption(_s.CurrentTeamId, $"{_s.CurrentTeamName} (your club)"));
            foreach (var t in _s.LeagueTeams()
                         .Where(t => t.Id != _s.CurrentTeamId).OrderBy(t => t.Name))
                Clubs.Add(new SquadClubOption(t.Id, t.Name));
#pragma warning disable MVVMTK0034   // deliberate: the setter would reload a roster we are still building
            _selectedClub = Clubs.FirstOrDefault();   // backing field: no reload during ctor
#pragma warning restore MVVMTK0034
        }
        catch { /* club browsing is additive */ }
    }

    partial void OnSelectedClubChanged(SquadClubOption? value)
    {
        if (value is null) return;
        _viewTeamId = value.TeamId;
        OnPropertyChanged(nameof(IsOwnClub));
        OnPropertyChanged(nameof(ViewingOtherClub));
        LoadRoster(_viewTeamId);
        ApplyFilter();
        Selected = Rows.FirstOrDefault();
        // an empty roster (or the same null selection) never fires OnSelectedChanged
        RefreshScoutButton();
        RefreshRenewButton(Selected);
    }

    /// <summary>
    /// Show a club's roster, whoever it is. BuildClubList only covers YOUR leagues, so a focus
    /// arriving from another division (or from a squad in a competition you don't play in)
    /// appends its own option rather than silently doing nothing.
    /// </summary>
    private void SelectClub(int teamId, string name)
    {
        if (teamId == _viewTeamId) return;   // already the roster on screen
        var option = Clubs.FirstOrDefault(c => c.TeamId == teamId);
        if (option is null)
        {
            var label = name.Length > 0 ? name : _s.TeamName(teamId);
            option = new SquadClubOption(teamId, label);
            Clubs.Add(option);
        }
        SelectedClub = option;   // OnSelectedClubChanged does the reload
    }

    /// <summary>
    /// Open focused on an entity (Nav.Go payload). A player pulls his club up first — the
    /// Squad screen is the profile view, so "view profile" on someone else's winger has to
    /// land on that club's roster with him selected, not on your own squad.
    /// </summary>
    public void Focus(EntityRef target)
    {
        try
        {
            if (target.Kind == EntityKind.Club)
            {
                SelectClub((int)target.Id, target.Name);
                return;
            }
            if (target.Kind != EntityKind.Player) return;

            var (teamId, club) = _s.ClubOfPlayer(target.Id);
            var name = target.Name.Length > 0 ? target.Name : _s.PlayerNameOf(target.Id);
            if (teamId is null)
            {
                SquadStatus = $"{name} is a free agent — open him in the Market.";
                return;
            }
            SelectClub(teamId.Value, club);
            var row = Rows.FirstOrDefault(r => r.PlayerId == target.Id);
            if (row is null)
            {
                // the search box or a filter chip can be hiding him — clear both and look again
                SquadSearch = "";
                ActiveChip = "All";
                row = Rows.FirstOrDefault(r => r.PlayerId == target.Id);
            }
            if (row is not null) Selected = row;
            else SquadStatus = $"{name} is out on loan or in a youth squad — not on this roster.";
        }
        catch { /* focused navigation must never take the screen down */ }
    }

    /// <summary>Guard for management actions: they only apply to your own club.</summary>
    private bool NotYourClub()
    {
        if (IsOwnClub) return false;
        SquadStatus = "You can only manage your own club — this is a scouting view.";
        return true;
    }

    public override string Title => "Squad";
    public override string Icon => "👥";

    public ObservableCollection<SquadEntry> Rows { get; } = new();

    // --- roster search + filter chips (P6 UX): find the player you mean, fast ----------

    private readonly List<SquadEntry> _all = new();
    private int _asOfMd;

    public IReadOnlyList<FilterChipVm> FilterChips { get; } =
        new[] { "All", "GK", "DEF", "MID", "FWD", "Injured", "Suspended", "Tired", "Unhappy", "Listed" }
            .Select(n => new FilterChipVm(n) { IsActive = n == "All" }).ToList();

    [ObservableProperty] private string _squadSearch = "";
    [ObservableProperty] private string _activeChip = "All";

    partial void OnSquadSearchChanged(string value) => ApplyFilter();

    partial void OnActiveChipChanged(string value)
    {
        foreach (var c in FilterChips) c.IsActive = c.Name == value;
        ApplyFilter();
    }

    [RelayCommand] private void SetChip(FilterChipVm chip) => ActiveChip = chip.Name;

    // Loans (P-next): out from the card, recalls from the loans strip.
    public ObservableCollection<LoanRowVm> Loans { get; } = new();
    public bool HasLoans => Loans.Count > 0;

    private void ReloadLoans()
    {
        Loans.Clear();
        try
        {
            foreach (var l in _s.ActiveLoans())
            {
                var line = l.Direction == "out"
                    ? $"{l.Player} → {l.OtherClub} (until June)"
                    : $"{l.Player} — on loan from {l.OtherClub}";
                Loans.Add(new LoanRowVm(l.PlayerId, l.Player, l.Direction, line));
            }
        }
        catch { /* loans are additive */ }
        OnPropertyChanged(nameof(HasLoans));
    }

    // --- the shared right-click vocabulary (EntityActions) ----------------------------

    /// <summary>
    /// Menu for a roster row. EntityActions reads the player's real club, so a browsed club's
    /// rows come back with the foreign set (scout · enquiry · shortlist · open in Market) —
    /// which is the whole exit from the read-only scouting view. Own rows get one extra verb
    /// the Squad screen owns: pin his radar for comparison.
    /// </summary>
    public ContextMenu? MenuFor(SquadEntry row)
    {
        if (row is null) return null;
        // Guarded like Market.MenuFor and Player.BuildMenu, the two sibling builders: this runs
        // inside a click's input dispatch, where a throw is a gesture that does nothing (or a
        // window that goes down) rather than a menu that failed. No menu is the honest outcome
        // — the caller says so on the status line — a dead gesture is not.
        try
        {
            List<MenuItem>? extras = null;
            if (IsOwnClub)
            {
                var pin = new MenuItem { Header = "📌 Pin for compare" };
                pin.Click += (_, _) => PinCompare();
                extras = new List<MenuItem> { pin };
            }
            return EntityActions.BuildMenu(_s, EntityRef.Player(row.PlayerId, row.Name),
                status: t => SquadStatus = t, refresh: Reload, extras: extras);
        }
        catch (Exception ex)
        {
            Program.Log("Squad.MenuFor", ex);
            return null;
        }
    }

    /// <summary>Menu for a loans-strip row — the loanee is a player like any other.</summary>
    public ContextMenu? MenuForLoan(LoanRowVm row)
    {
        if (row is null) return null;
        try
        {
            return EntityActions.BuildMenu(_s, EntityRef.Player(row.PlayerId, row.Name),
                status: t => SquadStatus = t, refresh: Reload);
        }
        catch (Exception ex)
        {
            Program.Log("Squad.MenuForLoan", ex);
            return null;
        }
    }

    /// <summary>
    /// What the docked status line says when a row's menu could not be produced — the ⋯ (and
    /// the right-click behind it) must never simply do nothing. THE BUG: both ⋯ handlers
    /// returned in silence on a null or empty menu, and EntityActions.BuildMenu's backstop hands
    /// back an EMPTY menu when the Session throws before a single verb is built, so one bad read
    /// turned the newly visible trigger back into a button that did nothing at all. The line
    /// names the other way in: the card's button for a roster row, the double-click for a loanee
    /// (who is not on the roster, so has no card).
    /// </summary>
    public void SayMenuUnavailable(string name, bool onLoan = false)
    {
        var whose = name.Length > 0 ? $"{name}'s" : "his";
        SquadStatus = onLoan
            ? $"Couldn't bring up {whose} options just now — double-click his line to open his profile, or try again."
            : $"Couldn't bring up {whose} options just now — open his full profile from the card, or try again.";
    }

    /// <summary>
    /// Leave the rail for the real screen — the same destination as double-clicking his row and
    /// as "👤 View profile" on the shared menu.
    /// THE BUG: the card beside the roster was a dead end. Single-click is the only gesture this
    /// screen ever taught, and single-click only fills that 336px column, so a manager clicked a
    /// name, got the cramped card, and concluded the app had no player screen at all.
    /// </summary>
    [RelayCommand]
    private void OpenProfile()
    {
        if (Selected is not { } p) { SquadStatus = "Pick a player first."; return; }
        Nav.Go("Player", EntityRef.Player(p.PlayerId, p.Name));
    }

    /// <summary>
    /// Re-read everything the menu verbs can have changed (a loan out empties a roster slot,
    /// a demotion moves him to the U21s), keeping the same player selected where he survives.
    /// </summary>
    public void Reload()
    {
        var keep = Selected?.PlayerId;
        LoadRoster(_viewTeamId);
        ApplyFilter();
        Selected = Rows.FirstOrDefault(r => r.PlayerId == keep) ?? Rows.FirstOrDefault();
        RefreshScoutButton();
        RefreshRenewButton(Selected);
        ReloadLoans();
    }

    [RelayCommand]
    private void LoanOut()
    {
        if (Selected is null || NotYourClub()) return;
        var pid = Selected.PlayerId;
        SquadStatus = _s.LoanOut(pid);
        // If the loan went through he's no longer in the squad — drop the row.
        if (!_s.Repo.Squad(_s.CurrentTeamId).Any(m => m.PlayerId == pid))
        {
            _all.RemoveAll(e => e.PlayerId == pid);
            ApplyFilter();
            Selected = Rows.FirstOrDefault();
        }
        ReloadLoans();
    }

    [RelayCommand]
    private void RecallLoan(LoanRowVm loan)
    {
        SquadStatus = _s.RecallLoan(loan.PlayerId);
        Reload();   // he walks back into the roster, so the grid has to see him
    }

    private void ApplyFilter()
    {
        var q = SquadSearch?.Trim() ?? "";
        IEnumerable<SquadEntry> set = _all;
        set = ActiveChip switch
        {
            "GK" => set.Where(p => p.Position == "GK"),
            "DEF" => set.Where(p => Visuals.PositionCategory(p.Position) == "DEF"),
            "MID" => set.Where(p => Visuals.PositionCategory(p.Position) == "MID"),
            "FWD" => set.Where(p => Visuals.PositionCategory(p.Position) == "FWD"),
            // one definition of "injured" for the whole screen: the chip, the badge and the
            // Absence line must never disagree about who can play
            "Injured" => set.Where(p => p.IsInjured),
            "Suspended" => set.Where(p => p.IsSuspended),
            "Tired" => set.Where(p => p.Fatigue >= 40),
            "Unhappy" => set.Where(p => p.Morale < 40),
            "Listed" => set.Where(p => _s.IsTransferListed(p.PlayerId)),
            _ => set,
        };
        if (q.Length > 0)
        {
            set = set.Where(p => p.Name.Contains(q, StringComparison.OrdinalIgnoreCase));
        }
        Rows.Clear();
        foreach (var p in set) Rows.Add(p);
        if (Selected is null || !Rows.Contains(Selected)) Selected = Rows.FirstOrDefault();
    }

    [ObservableProperty] private SquadEntry? _selected;
    [ObservableProperty] private IReadOnlyList<AbilityEntry> _abilities = Array.Empty<AbilityEntry>();
    [ObservableProperty] private Points _radarPoints = new();

    // Radar axis labels follow the player: GK axes are gk_* abilities (Visuals.GkRadarGroups),
    // so outfield SHO/PAS/... labels would lie on a keeper's card. Order matches the groups.
    private static readonly IReadOnlyList<string> OutfieldRadarLabels =
        new[] { "SHO", "PAS", "DRI", "SPD", "DEF", "STR" };
    private static readonly IReadOnlyList<string> GkRadarLabels =
        new[] { "AWR", "PAS", "HAN", "REF", "PAR", "REA" };
    [ObservableProperty] private IReadOnlyList<string> _radarLabels =
        new[] { "SHO", "PAS", "DRI", "SPD", "DEF", "STR" };

    /// <summary>A barely-scouted player (knowledge &lt; 45) shows no radar polygon.</summary>
    [ObservableProperty] private bool _radarMasked;

    // Season stats + contract + management state for the selected player.
    [ObservableProperty] private string _seasonLine = "";
    [ObservableProperty] private string _contractLine = "";
    [ObservableProperty] private bool _isCaptain;
    [ObservableProperty] private string _listLabel = "Transfer-list";
    [ObservableProperty] private string _squadStatus = "";

    // Compare: pin one player's radar, overlay the next selection's.
    [ObservableProperty] private Points _pinnedPoints = new();
    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(HasPinned))]
    private string _pinnedName = "";
    public bool HasPinned => PinnedName.Length > 0;

    // Card data is computed lazily — only the selected player's abilities are ever queried.
    partial void OnSelectedChanged(SquadEntry? value)
    {
        // Everything on this card that is MID-ACTION belongs to one player, so moving the
        // selection has to end it — all of it, in one place.
        //   • the two-step confirms (Release, Renew) disarm;
        //   • so do the contract talks. THE BUG: only Release was disarmed here, and Negotiating
        //     plus the round counter survived the selection change — open talks with A, make an
        //     offer, click B, and B's card showed A's negotiation armed and mid-round, so the
        //     next offer was made in the wrong man's name. Talks are cheap to reopen and an
        //     offer against the wrong player is not, so leaving a player always ends them.
        ReleaseArmed = false;
        ReleaseLabel = ReleaseIdle;
        EndNegotiation();
        RefreshScoutButton();
        RefreshRenewButton(value);
        if (value is null || value.PlayerId <= 0)
        {
            Abilities = Array.Empty<AbilityEntry>();
            RadarPoints = new Points();
            RadarMasked = false;
            RadarLabels = OutfieldRadarLabels;
            SeasonLine = "";
            ContractLine = "";
            return;
        }
        // THE BUG: this was the one database read in here with no guard — a live query against
        // the 2.2 GB career file, while every neighbour below it (reveal order, analysis, coach
        // report, season stats) already had one. A throw here left this method through the
        // Selected setter, and on the ⋯ path that meant the UI thread mid-input-dispatch. An
        // unreadable set of abilities is shown as NOTHING, never as a row of 40s: an empty
        // dictionary would have drawn a collapsed radar and analysed a man who has no attributes.
        IReadOnlyDictionary<string, int> abilities;
        var abilitiesUnread = false;
        try { abilities = _s.Repo.Attributes(value.PlayerId); }
        catch (Exception ex)
        {
            Program.Log("Squad.OnSelectedChanged: Repo.Attributes", ex);
            abilities = new Dictionary<string, int>();
            abilitiesUnread = true;
            SquadStatus = $"Couldn't read {value.Name}'s abilities just now — the rest of his card still stands.";
        }
        var isGk = value.Position == "GK";
        RadarLabels = isGk ? GkRadarLabels : OutfieldRadarLabels;
        // Knowledge gate (P6): same 45 threshold as the Market profile — below it the radar
        // would be a guess dressed up as data, so it hides behind a scout-him note.
        RadarMasked = value.Knowledge < 45;
        RadarPoints = RadarMasked || abilitiesUnread
            ? new Points()
            : BuildRadarPoints(Visuals.RadarAxes(abilities, isGk));
        // Knowledge-gated: your club is fully known, a browsed club only as deep as scouted —
        // and a famous man gives up what he is famous for whether you have watched him or not.
        ML.Core.Development.RevealOrder order;
        try { order = _s.RevealOrderOf(value.PlayerId, value.Position); }
        catch { order = ML.Core.Development.RevealOrder.Anonymous(value.PlayerId); }
        Abilities = abilitiesUnread
            ? Array.Empty<AbilityEntry>()
            : BuildAbilityList(abilities, isGk, FmMode, value.Knowledge, value.PlayerId, order);

        // The MFL analysis panels (UX P3): six graded-statement categories — the north star.
        try
        {
            AnalysisPanels = abilitiesUnread ? new List<AnalysisPanelVm>() : ML.Core.Development.PlayerAnalysis
                .Build(value.PlayerId, abilities, isGk, value.Knowledge, order)
                .Select(p => new AnalysisPanelVm(p.Name, p.Lines.Select(l => new AnalysisLineVm(
                    l.Text, l.Grade,
                    l.Tone switch
                    {
                        ML.Core.Development.PlayerAnalysis.Tone.Good => "✓",
                        ML.Core.Development.PlayerAnalysis.Tone.Mid => "○",
                        _ => "✗",
                    },
                    Visuals.Brush(l.Tone switch
                    {
                        ML.Core.Development.PlayerAnalysis.Tone.Good => "#1F9D4D",
                        ML.Core.Development.PlayerAnalysis.Tone.Mid => "#8A93A2",
                        _ => "#D64545",
                    }))).ToList()))
                .ToList();
        }
        catch { AnalysisPanels = Array.Empty<AnalysisPanelVm>(); }

        // Transfer / Value / Absence tab lines (real market + condition data).
        RefreshTransferLines(value.PlayerId);
        AbsenceLine = value.IsSuspended
            ? $"🟥 Suspended — {Session.SuspensionSpan(value.SuspendedMatches)} ({value.SuspendedReason})"
            : value.IsInjured
            ? $"🚑 Injured — unavailable until matchday {value.InjuredUntil}"
            : value.Fatigue >= 40 ? "😮‍💨 Exhausted — needs rest before he breaks down"
            // Healed. The stale injured_until_md is still on the row (it is only cleared at
            // season rollover), so name the date as history instead of letting it read as an
            // absence — the same stale flag that used to keep the red badge lit until April.
            : value.InjuredUntil is int back ? $"Fit again — back since matchday {back}"
            : value.Fatigue >= 20 ? "Match-fit, carrying normal fatigue"
            : "Fully fit and available";
        try
        {
            CoachLines = _s.CoachReportOf(value.PlayerId, value.Position)
                .Select(l => "• " + l).ToList();
            AnalystLine = _s.AnalystLineOf(value.PlayerId);
        }
        catch { CoachLines = Array.Empty<string>(); AnalystLine = ""; }
        try
        {
            var (apps, goals, assists, yellows, reds, avg) = _s.PlayerSeasonStats(value.PlayerId);
            SeasonLine = $"{Visuals.Plural(apps, "app")} · {Visuals.Plural(goals, "goal")} · {Visuals.Plural(assists, "assist")} · {yellows}🟨 {reds}🟥" +
                         (avg is { } a ? $" · {a:0.0} avg" : "");
            ContractLine = BuildContractLine(value.PlayerId);
            IsCaptain = _s.Captain == value.PlayerId;
            PromiseLine = _s.PromiseLine(value.PlayerId);
            var (det, _, _, _) = _s.TraitsOf(value.PlayerId);
            // qualitative, never "9/20" (UX audit): determination becomes a word
            var detWord = det >= 16 ? "Driven" : det >= 11 ? "Steady" : det >= 6 ? "Inconsistent" : "Flaky";
            CharacterLine = $"{_s.PersonalityOf(value.PlayerId)}  ·  {detWord}";
            _syncingPt = true;
            var ptStatus = _s.PlayTimeStatusOf(value.PlayerId);
            SelectedPtStatus = ptStatus;
            _syncingPt = false;
            RefreshPlayTimeLine(value.PlayerId, ptStatus);
            var skills = _s.SkillsOf(value.PlayerId);
            SkillsLine = skills.Count > 0 ? $"Skills: {string.Join(", ", skills)}" : "";
            CareerRows = _s.PlayerCareerHistory(value.PlayerId)
                .Select(h => $"{h.Year}/{(h.Year + 1) % 100:00}  ·  {h.Club}  ·  {h.Apps} apps · " +
                             $"{h.Goals}g {h.Assists}a" + (h.AvgRating is { } a2 ? $" · {a2:0.0} avg" : ""))
                .ToList();
        }
        catch { SeasonLine = ""; ContractLine = ""; PromiseLine = ""; CareerRows = Array.Empty<string>(); }
    }

    // Character + skills for the card (P1).
    [ObservableProperty] private string _characterLine = "";
    [ObservableProperty] private string _skillsLine = "";

    // The MFL card (UX P3): graded analysis panels + tab data.
    public sealed record AnalysisLineVm(string Text, string Grade, string Icon, IBrush IconBrush);
    public sealed record AnalysisPanelVm(string Name, IReadOnlyList<AnalysisLineVm> Lines);
    [ObservableProperty] private IReadOnlyList<AnalysisPanelVm> _analysisPanels = Array.Empty<AnalysisPanelVm>();
    [ObservableProperty] private string _marketValueLine = "";
    [ObservableProperty] private string _wageLine = "";
    [ObservableProperty] private string _transferStatusLine = "";
    [ObservableProperty] private string _absenceLine = "";
    [ObservableProperty] private string _loanListLabel = "↔ Loan-list";

    /// <summary>
    /// The Transfer tab's three lines. The status chip is the imported player_market row
    /// OVERLAID with your own meta flags — the transfer- and loan-list toggles write meta, so
    /// a chip that only read the import would sit there contradicting the button beside it.
    /// </summary>
    private void RefreshTransferLines(long playerId)
    {
        string? imported = null;
        try
        {
            using var mc = _s.Db.Connection.CreateCommand();
            mc.CommandText = "SELECT COALESCE(value,0), COALESCE(wage,0), transfer_status " +
                             "FROM player_market WHERE player_id=$p";
            mc.Parameters.AddWithValue("$p", playerId);
            using var r = mc.ExecuteReader();
            if (r.Read())
            {
                MarketValueLine = $"Market value  £{r.GetInt64(0):N0}";
                WageLine = r.GetInt64(1) > 0 ? $"Wage  £{r.GetInt64(1):N0}/wk" : "";
                imported = r.IsDBNull(2) ? "" : r.GetString(2);
            }
            else { MarketValueLine = ""; WageLine = ""; }
        }
        catch { MarketValueLine = ""; WageLine = ""; imported = null; }

        var listed = false;
        var loanListed = false;
        // Meta flags are keyed on YOUR club, so a browsed club's players simply read false.
        try { listed = _s.IsTransferListed(playerId); loanListed = _s.IsLoanListed(playerId); }
        catch { /* labels are additive */ }

        var labels = new List<string>();
        if (listed || imported == "listed") labels.Add("TRANSFER LISTED");
        if (loanListed || imported == "loan-listed") labels.Add("AVAILABLE ON LOAN");
        if (labels.Count == 0 && imported == "not-for-sale") labels.Add("NOT FOR SALE");
        TransferStatusLine = labels.Count > 0 ? string.Join("  ·  ", labels)
            : imported is null ? ""
            : "Open to offers";

        ListLabel = listed ? "Un-list" : "Transfer-list";
        LoanListLabel = loanListed ? "↔ Un-loan-list" : "↔ Loan-list";
    }

    // Playing time (P5, FM-style): status drives morale AND the AI's willingness to sell.
    public IReadOnlyList<string> PtStatusOptions => Session.PlayTimeStatuses;
    private bool _syncingPt;
    [ObservableProperty] private string? _selectedPtStatus;
    [ObservableProperty] private string _playTimeLine = "";

    partial void OnSelectedPtStatusChanged(string? value)
    {
        // IsOwnClub: the picker is hidden in scouting view, but the sync when browsing another
        // roster must never write a play-time promise into someone else's squad.
        if (_syncingPt || value is null || Selected is null || !IsOwnClub) return;
        SquadStatus = _s.SetPlayTimeStatus(Selected.PlayerId, value);
        RefreshPlayTimeLine(Selected.PlayerId, value);
    }

    private void RefreshPlayTimeLine(long playerId, string status)
    {
        try
        {
            var expected = Session.ExpectedStartsPer6(status);
            var md = _s.NextFixture()?.Matchday ?? 6;
            var actual = _s.StartsInLastSix(playerId, Math.Max(1, md - 1));
            PlayTimeLine = expected < 0
                ? $"No playing-time promise · started {actual} of the last 6"
                : $"Wants {expected} of every 6 starts · got {actual}" +
                  (actual < expected - 1 ? "  ⚠ unhappy" : actual >= expected ? "  ✓ content" : "");
        }
        catch { PlayTimeLine = ""; }
    }

    // FM display toggle + the permanent reports (P5).
    [ObservableProperty] private bool _fmMode;
    [ObservableProperty] private IReadOnlyList<string> _coachLines = Array.Empty<string>();
    public bool HasCoachLines => CoachLines.Count > 0;
    partial void OnCoachLinesChanged(IReadOnlyList<string> value) => OnPropertyChanged(nameof(HasCoachLines));
    [ObservableProperty] private string _analystLine = "";

    partial void OnFmModeChanged(bool value)
    {
        _s.FmAttributeMode = value;
        // Rebuild the card under the new display mode.
        var cur = Selected;
        Selected = null;
        Selected = cur;
    }

    // Season-by-season career lines for the card (D3).
    [ObservableProperty] private IReadOnlyList<string> _careerRows = Array.Empty<string>();
    public bool HasCareerRows => CareerRows.Count > 0;
    partial void OnCareerRowsChanged(IReadOnlyList<string> value) => OnPropertyChanged(nameof(HasCareerRows));

    [ObservableProperty] private string _promiseLine = "";

    // --- contract negotiation (B3): multi-round with the agent -----------------------
    [ObservableProperty] private bool _negotiating;
    [ObservableProperty] private decimal _wageOffer;
    [ObservableProperty] private string _selectedYears = "2";
    [ObservableProperty] private string _selectedStatus = "None";
    [ObservableProperty] private string _negotiationLine = "";
    private int _round = 1;

    public IReadOnlyList<string> YearsOptions { get; } = new[] { "1", "2", "3" };
    public IReadOnlyList<string> StatusOptions { get; } = new[] { "None", "Rotation", "First-team", "Star" };

    [RelayCommand]
    private void OpenNegotiation()
    {
        if (Selected is null || NotYourClub()) return;
        _round = 1;
        var (demand, line) = _s.ContractDemand(Selected.PlayerId, int.Parse(SelectedYears), SelectedStatus);
        WageOffer = demand;
        NegotiationLine = line;
        Negotiating = true;
    }

    [RelayCommand]
    private void MakeOffer()
    {
        if (Selected is null || !Negotiating || NotYourClub()) return;
        var (accepted, over, message) = _s.OfferContract(
            Selected.PlayerId, (long)WageOffer, int.Parse(SelectedYears), SelectedStatus, _round);
        if (over)
        {
            Negotiating = false;
            _round = 1;   // the next player's talks start at round one, not this man's third
            // The panel is only visible while Negotiating, so the agent's last word has to move
            // to the status line or the outcome vanishes with the border around it.
            SquadStatus = message;
            NegotiationLine = "";
            if (accepted)
            {
                // the full line, not a bare year — the learned positions and the LISTED flag
                // are part of what the contract row says and must not be dropped on a signing
                ContractLine = BuildContractLine(Selected.PlayerId);
                PromiseLine = _s.PromiseLine(Selected.PlayerId);
            }
        }
        else
        {
            _round++;
            NegotiationLine = message;
        }
    }

    [RelayCommand]
    private void CancelNegotiation() => EndNegotiation();

    /// <summary>
    /// Close the talks and forget the round. Called by "Walk away" AND by every selection change —
    /// a negotiation is one player's, and its state must never be inherited by the next man.
    /// </summary>
    private void EndNegotiation()
    {
        Negotiating = false;
        _round = 1;
        NegotiationLine = "";
    }

    [RelayCommand]
    private void Praise()
    {
        if (Selected is null || NotYourClub()) return;
        SquadStatus = _s.TalkTo(Selected.PlayerId, Selected.Name, praise: true);
    }

    [RelayCommand]
    private void Criticise()
    {
        if (Selected is null || NotYourClub()) return;
        SquadStatus = _s.TalkTo(Selected.PlayerId, Selected.Name, praise: false);
    }

    [RelayCommand]
    private void PromiseStarts()
    {
        if (Selected is null || NotYourClub()) return;
        SquadStatus = _s.MakePromise(Selected.PlayerId, Selected.Name, "starts");
        PromiseLine = _s.PromiseLine(Selected.PlayerId);
    }

    [RelayCommand]
    private void PromiseContract()
    {
        if (Selected is null || NotYourClub()) return;
        SquadStatus = _s.MakePromise(Selected.PlayerId, Selected.Name, "contract");
        PromiseLine = _s.PromiseLine(Selected.PlayerId);
    }

    [RelayCommand]
    private void MakeCaptain()
    {
        if (Selected is null || NotYourClub()) return;
        _s.Captain = Selected.PlayerId;
        IsCaptain = true;
        SquadStatus = $"{Selected.Name} is your captain.";
    }

    [RelayCommand]
    private void ToggleList()
    {
        if (Selected is null || NotYourClub()) return;
        var now = !_s.IsTransferListed(Selected.PlayerId);
        _s.SetTransferListed(Selected.PlayerId, now);
        SquadStatus = now
            ? $"{Selected.Name} transfer-listed — offers are far more likely next window."
            : $"{Selected.Name} taken off the list.";
        RefreshTransferLines(Selected.PlayerId);
        ContractLine = BuildContractLine(Selected.PlayerId);   // its "· LISTED" flag just moved
    }

    /// <summary>The loan shop window: a label only — LoanOut still does the moving.</summary>
    [RelayCommand]
    private void ToggleLoanList()
    {
        if (Selected is null || NotYourClub()) return;
        var now = !_s.IsLoanListed(Selected.PlayerId);
        _s.SetLoanListed(Selected.PlayerId, now);
        SquadStatus = now
            ? $"{Selected.Name} is available on loan — clubs short of bodies will ask."
            : $"{Selected.Name} is off the loan list.";
        RefreshTransferLines(Selected.PlayerId);
    }

    /// <summary>Actively shop him around: lists him and rings the agents now, not next preseason.</summary>
    [RelayCommand]
    private void OfferToClubs()
    {
        if (Selected is null || NotYourClub()) return;
        SquadStatus = _s.OfferToClubs(Selected.PlayerId);
        RefreshTransferLines(Selected.PlayerId);
    }

    // --- release: a two-step confirm, because a free transfer can't be undone -----------
    private const string ReleaseIdle = "⛔ Release";
    private const string ReleaseArm = "⛔ Sure? Release";
    [ObservableProperty] private string _releaseLabel = ReleaseIdle;
    [ObservableProperty] private bool _releaseArmed;

    [RelayCommand]
    private void Release()
    {
        if (Selected is null || NotYourClub()) return;
        if (!ReleaseArmed)
        {
            ReleaseArmed = true;
            ReleaseLabel = ReleaseArm;
            SquadStatus = $"Release {Selected.Name} on a free? Click again to confirm.";
            return;
        }
        ReleaseArmed = false;
        ReleaseLabel = ReleaseIdle;
        var name = Selected.Name;
        var msg = _s.ReleasePlayer(Selected.PlayerId);
        SquadStatus = $"{name}: {msg}";
        if (msg.StartsWith("Released"))
        {
            var gone = Selected;
            _all.RemoveAll(e => e.PlayerId == gone.PlayerId);
            Rows.Remove(gone);
            Selected = Rows.FirstOrDefault();
        }
    }

    // --- send the scout out from the card (the browsed-club exit from "read-only") ------
    [ObservableProperty] private string _scoutButtonLabel = "🔍 Send scout";
    [ObservableProperty] private bool _canScout;

    /// <summary>
    /// Keeps the card's scout button honest: it says WHY it is disabled rather than sitting
    /// there greyed out with no reason, exactly as the shared menu does.
    /// </summary>
    private void RefreshScoutButton()
    {
        try
        {
            var noScout = _s.StaffFor("Scout") is null;
            var busy = _s.ActiveScoutJob() is not null;
            CanScout = ViewingOtherClub && !noScout && !busy;
            // The label carries the refusal (a greyed button with no reason is the thing the
            // UX audit keeps catching); kept short so it fits beside the 200px radar.
            ScoutButtonLabel = noScout ? "🔍 No scout on the books"
                : busy ? "🔍 Scout is on a mission"
                : "🔍 Send scout";
        }
        catch { CanScout = false; ScoutButtonLabel = "🔍 Send scout"; }
    }

    [RelayCommand]
    private void ScoutSelected()
    {
        if (Selected is null) return;
        SquadStatus = _s.StartScoutJob("player", Selected.PlayerId, Selected.Name);
        RefreshScoutButton();
    }

    // --- renew: priced, and a two-step confirm, because it spends real money ------------
    //
    // THE BUG: "Renew +2yrs" was one click, and SessionSquad.RenewContract charges a signing
    // bonus of 10% of the player's valuation — millions, silently. Worse, the old code then
    // overwrote ContractLine UNCONDITIONALLY, so when the club could not cover the bonus the
    // line re-rendered as if the deal had gone through and the manager could not tell whether
    // the money had left. Release is two-step because it cannot be undone; renewing cannot be
    // undone EITHER and it costs, so it gets the same arm — with the price on the button, so
    // the number is known before the first click, not after the second.
    private const string RenewIdle = "📃 Renew +2yrs";
    [ObservableProperty] private string _renewLabel = RenewIdle;
    [ObservableProperty] private bool _renewArmed;
    private long _renewBonus;

    /// <summary>
    /// Put this player's signing bonus on the button, and disarm — a price belongs to one man.
    /// </summary>
    private void RefreshRenewButton(SquadEntry? player)
    {
        RenewArmed = false;
        _renewBonus = 0;
        if (player is null || !IsOwnClub) { RenewLabel = RenewIdle; return; }
        try
        {
            // Mirror SessionSquad.RenewContract's OWN inputs exactly, or the button would quote a
            // price the engine never charges: it reads overall_rating defaulted to 65 and a null
            // age (our roster row COALESCEs both to 0), and it prices off the synthetic
            // ValuationOf curve — deliberately NOT the imported market value.
            var rating = player.Rating > 0 ? player.Rating : 65;
            var age = player.Age > 0 ? (int?)player.Age : null;
            _renewBonus = Session.ValuationOf(rating, age) / 10;
            RenewLabel = $"{RenewIdle} · £{_renewBonus:N0}";
        }
        catch { RenewLabel = RenewIdle; }
    }

    [RelayCommand]
    private void Renew()
    {
        if (Selected is null || NotYourClub()) return;
        if (!RenewArmed)
        {
            RenewArmed = true;
            RenewLabel = $"📃 Sure? £{_renewBonus:N0}";
            SquadStatus = $"Renewing {Selected.Name} costs a £{_renewBonus:N0} signing bonus, " +
                          "paid the moment you confirm. Click again to go ahead.";
            return;
        }
        var msg = _s.RenewContract(Selected.PlayerId);
        SquadStatus = msg;
        // Only the engine's success answer rewrites the contract line. Its refusal ("you can't
        // cover it") leaves the old line standing and says so in the status, so a renewal that
        // did not happen never looks like one that did.
        if (msg.Contains("signed until", StringComparison.Ordinal))
            ContractLine = BuildContractLine(Selected.PlayerId);
        RefreshRenewButton(Selected);   // disarm, and re-price for his new deal
    }

    /// <summary>
    /// The contract row as the card states it everywhere: the expiry year, the positions he has
    /// learned, and the transfer-list flag. One builder, so a renewal or a signing can never
    /// re-render a shorter version of the same fact.
    /// </summary>
    private string BuildContractLine(long playerId)
    {
        try
        {
            var learned = _s.LearnedPositions(playerId);
            return $"Contract until {_s.ContractYear(playerId)}" +
                   (learned.Count > 0 ? $" · plays {string.Join("/", learned)} too" : "") +
                   (_s.IsTransferListed(playerId) ? " · LISTED" : "");
        }
        catch { return ContractLine; }
    }

    [RelayCommand]
    private void PinCompare()
    {
        if (Selected is null) return;
        PinnedPoints = RadarPoints;
        PinnedName = Selected.Name;
        SquadStatus = $"{Selected.Name} pinned — select another player to compare radars.";
    }

    [RelayCommand]
    private void ClearCompare()
    {
        PinnedPoints = new Points();
        PinnedName = "";
    }

    private static Points BuildRadarPoints((string Label, double Value)[] axes) =>
        PlayerCard.BuildRadarPoints(axes);

    private static IReadOnlyList<AbilityEntry> BuildAbilityList(
        IReadOnlyDictionary<string, int> abilities, bool isGk,
        bool fmMode = false, int knowledge = 100, long playerId = 0,
        ML.Core.Development.RevealOrder? order = null) =>
        PlayerCard.BuildAbilityList(abilities, isGk, fmMode, knowledge, playerId, order);

    private sealed record SquadRowDto
    {
        public long PlayerId { get; init; }
        public int Number { get; init; }
        public string Name { get; init; } = "";
        public string Position { get; init; } = "";
        public int Age { get; init; }
        public int Rating { get; init; }
        public string? Nationality { get; init; }
        public int? HeightCm { get; init; }
        public int? WeightKg { get; init; }
        public string? PortraitPath { get; init; }
        public string? Playstyle { get; init; }
        public int Fatigue { get; init; }
        public int? InjuredUntil { get; init; }
        public int SuspendedMatches { get; init; }
        public string SuspendedReason { get; init; } = "";
        public int Morale { get; init; }
    }
}
